version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    build:
      context: ./nodes
      dockerfile: Dockerfile
    command:
      --nodekeyhex="391a7d73f6e4936631d4f76cc64d94ec2bd6a08ae9f41da5abef651bf1289407"
      --nodiscover
      --ipcdisable
      --networkid=12345
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    build:
      context: ./nodes
      dockerfile: Dockerfile
    depends_on:
      - geth-bootnode
      - geth-miner
    command:
      --bootnodes="enode://14143fd744f4e71c7852ac9c58fafd096d95162b476a4739dcd7761c73c7ae52952c88563375ab1f4a3e5019267725292b196ee3f017fb7a3e1e8e713e52c9b0@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="http://localhost"
      --http.vhosts="*"
      --networkid=12345
      --netrestrict="172.16.254.0/28"
    ports:
      - "8545:8545"
    networks:
      priv-eth-net:

  geth-miner:
    hostname: geth-miner
    build:
      context: ./nodes
      dockerfile: Dockerfile
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://14143fd744f4e71c7852ac9c58fafd096d95162b476a4739dcd7761c73c7ae52952c88563375ab1f4a3e5019267725292b196ee3f017fb7a3e1e8e713e52c9b0@geth-bootnode:30303"
      --networkid=12345
      --mine
      --miner.etherbase=0x8De0c53FC169BA09F111aA4170697e8CF42CCbBe
      --unlock 0x8De0c53FC169BA09F111aA4170697e8CF42CCbBe
      --netrestrict="172.16.254.0/28"
      --password root/password.txt
    networks:
      priv-eth-net:

 # Server

  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=local
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - RPC_URL=${RPC_URL}
      - KEYSTORE_PATH=${KEYSTORE_PATH}
      - KEYSTORE_PASS=${KEYSTORE_PASS}
    depends_on:
      - db
    networks:
      priv-eth-net:

  db:
    hostname: db
    image: postgres:15-alpine
    container_name: postgres-15
    volumes:
      - ./rpc-server/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/Postgres_Test:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      priv-eth-net:

  cronjob:
    hostname: cronjob
    build:
      context: ./cronjob
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST=app
      - PORT=8080
      - TARGET_ADDRESS=0x8De0c53FC169BA09F111aA4170697e8CF42CCbBe
    depends_on:
      - app
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28
