// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chain/balance/{address}": {
            "get": {
                "description": "查詢指定帳戶餘額\n\nError code list\n- 400: PARAMETER_INVALID\n- 500: INTERNAL_PROCESS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chain"
                ],
                "summary": "查詢指定帳戶餘額",
                "parameters": [
                    {
                        "type": "string",
                        "description": "帳戶地址",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorMessageResponse"
                        }
                    }
                }
            }
        },
        "/chain/blocks/height": {
            "get": {
                "description": "查詢最新區塊高度\n\nError code list\n- 500: INTERNAL_PROCESS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chain"
                ],
                "summary": "查詢最新區塊高度",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BlockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorMessageResponse"
                        }
                    }
                }
            }
        },
        "/chain/faucet/{address}": {
            "post": {
                "description": "取得 0.02 測試幣 (模擬發送交易)\n\nError code list\n- 400: PARAMETER_INVALID\n- 500: INTERNAL_PROCESS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chain"
                ],
                "summary": "取得 0.02 測試幣 (模擬發送交易)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "接收帳戶地址",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorMessageResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BalanceResponse": {
            "description": "Balance response",
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "wei": {
                    "type": "integer"
                }
            }
        },
        "BlockResponse": {
            "description": "Block response",
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                }
            }
        },
        "ErrorMessageResponse": {
            "description": "Error message response for 4xx and 5xx errors",
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP status code",
                    "type": "integer",
                    "example": 400
                },
                "name": {
                    "description": "Error name (key)",
                    "type": "string",
                    "example": "PARAMETER_INVALID"
                }
            }
        },
        "SuccessMessageResponse": {
            "description": "Success message response for 200",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "name": {
                    "type": "string",
                    "example": "SUCCESS"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Ethereum Private Chain RPC Server",
	Description:      "Ethereum Private Chain RPC Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
